from typing import Any

from pydgraph.meta import VERSION as VERSION

__maintainer__: str
__status__: str

def is_string(string:Any) -> bool: ...
def is_jwt_expired(exception:Exception) -> bool: ...
def is_aborted_error(error:Any) -> bool: ...
def is_retriable_error(error:Exception) -> bool: ...
def is_connection_error(error:Exception) -> bool: ...
