from typing import Any

from grpc import Channel, UnaryUnaryMultiCallable
from pydgraph.proto.api_pb2 import Request, Response

class DgraphStub:
    Login: UnaryUnaryMultiCallable[Request, Response]
    Query: UnaryUnaryMultiCallable[Request, Response]
    Alter: UnaryUnaryMultiCallable[Request, Response]
    CommitOrAbort: UnaryUnaryMultiCallable[Request, Response]
    CheckVersion: UnaryUnaryMultiCallable[Request, Response]
    def __init__(self, channel:Channel) -> None: ...

class DgraphServicer:
    def Login(self, request:Request, context:Any) -> None: ...
    def Query(self, request:Request, context:Any) -> None: ...
    def Alter(self, request:Request, context:Any) -> None: ...
    def CommitOrAbort(self, request:Request, context:Any) -> None: ...
    def CheckVersion(self, request:Request, context:Any) -> None: ...

def add_DgraphServicer_to_server(servicer:DgraphServicer, server:Any) -> None: ...
